# Generated by Django 5.0.6 on 2024-07-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundimage',
            name='concept_option',
            field=models.CharField(max_length=500),
        ),
    ]
