# Generated by Django 5.0.6 on 2024-07-27 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texttovideo', '0002_alter_texttovideo_prompt_alter_texttovideo_video_url'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='texttovideo',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='texttovideo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='texttovideo',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
            preserve_default=False,
        ),
    ]
