# Generated by Django 5.0.6 on 2024-07-27 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texttovideo', '0003_texttovideo_is_deleted_texttovideo_updated_at_and_more'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='texttovideo',
            name='user_id',
        ),
        migrations.AddField(
            model_name='texttovideo',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
