version: "3.8"

services:
  mysqldb:
    build: ./db
    container_name: mysqldb
    env_file:
      - "./db/.env"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    restart: always
    depends_on:
      - mysqldb
    command: >
      bash -c "
      python wait_mysql.py && python manage.py makemigrations && python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysqldb:mysql
    ports:
      - "8001:80"
    environment:
      PMA_HOST: mysqldb
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
volumes:
  mysql_data:

