version: "3.8"

services:
  mysqldb:
    build: ./db
    container_name: mysqldb
    env_file:
      - "./db/.env"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - ./logs:/app/logs  # 로그 디렉토리 추가
    restart: always
    depends_on:
      - mysqldb
      - rabbitmq
      - redis
    env_file:
      - "./db/.env"
    command: >
      bash -c "python wait_mysql.py &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      gunicorn -w 4 -b 0.0.0.0:8000 backend.wsgi:application"

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"  # RabbitMQ Prometheus Exporter
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    command: >
      bash -c "rabbitmq-plugins enable rabbitmq_prometheus &&
      rabbitmq-server"

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  celery:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: celery
    volumes:
      - ./:/app
      - ./logs:/app/logs  # 로그 디렉토리 추가
    depends_on:
      - backend
      - rabbitmq
      - redis
    environment:
      GUNICORN_CMD_ARGS: "--timeout 300 --workers 4"
    command: >
      bash -c "python wait_mysql.py &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      gunicorn -w 4 -b 0.0.0.0:8000 --timeout 300 backend.wsgi:application"

volumes:
  mysql_data:
  rabbitmq_data:
