version: "3.8"

services:
  mysqldb:
    build: ./db
    container_name: mysqldb
    env_file:
      - "./db/.env"
    #mysql 환경 변수와 관련된 file은 현재 위치/db 하위에 .env파일로 따로 둠 #
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql  # MySQL 데이터를 지속적으로 유지하기 위한 볼륨 설정


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    restart: always
    depends_on:
      - mysqldb
    command:
      bash -c "python wait_mysql.py &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
volumes:
  mysql_data:
