global:
  # 전역 스크레이프 간격 설정 (기본값: 15초)
  scrape_interval: 15s

scrape_configs:
  - job_name: 'rabbitmq'
    # RabbitMQ 모니터링 대상 설정
    static_configs:
      - targets: ['rabbitmq:15692']

  - job_name: 'backend'
    # 백엔드 서비스 모니터링 대상 설정
    static_configs:
      - targets: ['backend:8000']

  - job_name: 'prometheus'
    # Prometheus 자체 모니터링 대상 설정
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    # Node Exporter 모니터링 대상 설정
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    # cAdvisor 모니터링 대상 설정
    static_configs:
      - targets: ['cadvisor:8080']
