# Generated by Django 5.0.6 on 2024-07-27 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0003_image_image_file_alter_image_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_file',
        ),
    ]
